/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import java.util.Scanner;

abstract class User {
    private String customIDKey;
    private String password;
    private String fullName;
    private String emailAddress;
    private String phone;

    public User(String customIDKey, String password, String fullName, String emailAddress, String phone) {
        this.customIDKey = customIDKey;
        this.password = password;
        this.fullName = fullName;
        this.emailAddress = emailAddress;
        this.phone = phone;
    }

    // Getters and setters for common attributes

    public void setPassword(String password) {
        this.password = password;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }


    public String getCustomIDKey() {
        return customIDKey;
    }

    public String getFullName() {
        return fullName;
    }

    public String getPassword() {
        return password;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    protected String getPhone() {
        return phone;
    }

    public boolean isAdmin() {
        return false; // By default, regular users are not admins
    }

    public void updateProfile() {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter user ID: ");
        String customID = scanner.nextLine();
        System.out.print("Enter which personal information you want to change(phone,hashPassword,fullName,email): ");
        String filter = scanner.nextLine();
        System.out.print("Enter new personal information: ");
        String newInfo = scanner.nextLine();
        JsonManagement.updateUserProfileJson(customID, filter, newInfo, UserManagement.userDBPath);
    }
}
